---

- name: regenerate grub2 conf
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: restart chronyd
  service: name=chronyd state=restarted

- name: restart ntpd
  service: name=ntpd state=restarted

- name: restart systemd-logind
  service: name=systemd-logind state=restarted

- include: ./preconfigure.yml
  tags:
    - hana-install
...
